name: everything-bucket
main: io.github.searls.scartissue.EverythingBucket
version: 0.0.1

commands:
   random:
      description: Generates a random block in front of the player
      usage: /random
